services:
  app:
    build: .
    container_name: wallet-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - mailpit
      - wiremock
    networks:
      - wallet-net

  db:
    image: postgres:16-alpine
    container_name: wallet-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: money_tracker_mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - wallet-net

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wallet-wiremock
    ports:
      - "8081:8080"
    command: "--verbose --global-response-templating"
    volumes:
      - ./mocks:/home/wiremock
    networks:
      - wallet-net

volumes:
  postgres_data:

networks:
  wallet-net:
    driver: bridge